name: Generate GitHub Stats & Snake

on:
  schedule:
    - cron: '0 0 * * *'  # اجرا هر روز ساعت 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Profile Summary & Snake SVG
        uses: lowlighter/github-profile-summary-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub stats and snake animation [skip ci]" || echo "No changes to commit"
          git push
